version: "3.9"

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend.Dockerfile
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    env_file:
      - apps/backend/.env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=production

  # Frontend UI
  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend.Dockerfile
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend

  # MariaDB Database
  mariadb:
    image: mariadb:10.9.3
    ports:
      - "3306:3306"
    volumes:
      - blenderi-volume:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=blenderi
      - MARIADB_USER=blenderi
      - MARIADB_PASSWORD=V3rySecretPasswor4
      - MARIADB_ROOT_PASSWORD=V3rySecretR00tPasswor4

  # Redis Cache
  redis:
    image: redis:7.0.5-alpine3.16
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data

volumes:
  blenderi-volume:
    name: blenderi-volume
  redis-volume:
    name: redis-volume
