# fly.toml app configuration file generated for tayttopaikka-backend on 2026-01-31T10:33:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tayttopaikka-backend'
primary_region = 'ams'
kill_timeout = '42s'

[deploy]
  strategy = 'canary'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '42s'
    method = 'GET'
    path = '/api/utils/heartbeat'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
